=== chinchifou/Scrabble2/savegames/template_save_game.xsd
<?xml version = "1.0" encoding="UTF-8" ?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:element name="Scrabble_savegame">
	    <xsd:complexType>
	        <xsd:sequence>

	        	<xsd:element name="Players">
	        		<xsd:complexType>
	        			<xsd:sequence>

	        				<xsd:element name="Player" maxOccurs="8">
	        					<xsd:complexType>
	        						<xsd:sequence>

										<xsd:element name="Name" type="xsd:normalizedString"/>
										<xsd:element name="Hand" type="xsd:normalizedString"/>
										<xsd:element name="Score" type="xsd:positiveInteger"/>

	        						</xsd:sequence>	        					
	        					</xsd:complexType>
	        				</xsd:element>

	        			</xsd:sequence>
	        		</xsd:complexType>
	        	</xsd:element>

	        	<xsd:element name="Board_state">	        		
	        		<xsd:complexType>
	        			<xsd:sequence>

						<xsd:element name="Row" type="xsd:normalizedString" minOccurs="15" maxOccurs="15"/>

	        			</xsd:sequence>
	        		</xsd:complexType>		
	        	</xsd:element>

	        	<xsd:element name="Bag_of_letters" type="xsd:normalizedString"/>

	        </xsd:sequence>
	        <xsd:attribute name="timestamp" type="xsd:dateTime" use="required"/>
	    </xsd:complexType>

	</xsd:element>

</xsd:schema>

=== chinchifou/Scrabble2/savegames/template_save_game.xml
<?xml version = "1.0" encoding="UTF-8" ?>

<!-- Document to save game -->
<Scrabble_savegame timestamp="2017-09-10T12:30:00" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="template_save_game.xsd">
	
	<Players>

		<Player>
			<Name>John_Doo</Name>
			<Hand>AZER*YU</Hand>
			<Score>123</Score>
		</Player>

		<Player>
			<Name>Mike_Hammer</Name>
			<Hand>AEAEAEF</Hand>
			<Score>41</Score>
		</Player>

	</Players>

	<Board_state>
		<Row>??????????????A</Row>
		<Row>??????????????W</Row>
		<Row>??????????????O</Row>
		<Row>??????????????R</Row>
		<Row>???????TESTWORD</Row>
		<Row>???????E???????</Row>
		<Row>???????S???????</Row>
		<Row>???????T???????</Row>
		<Row>???????I???????</Row>
		<Row>???????N???????</Row>
		<Row>???DOING???????</Row>
		<Row>???????????????</Row>
		<Row>???????????????</Row>
		<Row>???????????????</Row>
		<Row>???????????????</Row>
	</Board_state>

	<Bag_of_letters>AZERTYUIOPQDGJLMNVWPIUYTREZA</Bag_of_letters>
	
</Scrabble_savegame>
